# Generated by Django 4.2.9 on 2024-01-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://tse4.mm.bing.net/th?id=OIP.ISK0kbvLUbQTc9hltD47fAHaF0&pid=Api&P=0&h=220",
                max_length=500,
            ),
        ),
    ]
